Repository giotto-ai/giotto-ph, pull requests merged in 2021-11, with the labels that each got.

#42 Improve Notes section in ripser_parallel
  gph/python/ripser_interface.py
Labels: documentation

#43 [CPP] Remove zero diameter check for edges in 0-dim computation
  gph/python/test/test_ripser.py
  gph/src/ripser.h
Labels: bug

#48 [CI] Fix wheels after issues with pip version
  .github/workflows/wheels.yml
Labels: bug

#51 [CPP] Avoid unnecessary binary search when k = 1 (0-simplices)
  gph/src/ripser.h
Labels: enhancement
